version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      rede_local:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=petshop-api
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=petshop-system
    volumes:
      - /tmp/postgres-volume:/data/db
      - ./adapter/output/database/db/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      rede_local:

networks:
  rede_local: