version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      rede_local:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=petshop-system
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=petshop-system
    volumes:
      - /tmp/postgres-volume:/data/db
      - ./configuration/db/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      rede_local:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  petshop-admin-api:
    container_name: petshop-admin-api
    build: ../../../../../petshop-admin-api/
    restart: always
    environment:
      - SPRING_PROFILE=docker
      - REDIS_ADDR=redis:6379
      - DB_USER=petshop-system
      - DB_PASSWORD=test1234
      - DB_NAME=petshop-system
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_TYPE=postgres
    ports:
      - "5002:5002"
    expose:
      - "5002"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      rede_local:

  petshop-message-api:
    container_name: petshop-message-api
    build: ../../../../../petshop-message-api/
    restart: always
    environment:
      - SPRING_PROFILE=docker
    ports:
      - "5003:5003"
    expose:
      - "5003"
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
    networks:
      rede_local:

  petshop-api-gateway:
    container_name: petshop-api-gateway
    build: ../petshop-api-gateway
    restart: always
    ports:
      - "9999:9999"
    expose:
      - "9999"
    depends_on:
      petshop-admin-api:
        condition: service_started
      redis:
        condition: service_started
    networks:
      rede_local:

networks:
  rede_local: